# Generated by Django 4.1.10 on 2023-07-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattachment',
            old_name='user',
            new_name='product',
        ),
    ]
