# Generated by Django 4.1.10 on 2023-07-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_user_productattachment_product'),
    ]

    operations = [
       
    ]
